name: hpc
channels:
  - defaults
dependencies:
  - pip
  - python=3.8
  - pip:
    - torch==1.10.0
    - torchvision==0.11.1
    - torchaudio==0.10.0
    - ray[rllib]==2.2.0
    - gym==0.23
    - numpy
    - mlflow
    - pyyaml
    - func_timeout
    - ale-py==0.7.5
    - autorom
    - tqdm