name: hpc
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - opencv
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - setuptools==67.0
    - torch==1.12.1+cu113
    - torchvision==0.13.1+cu113
    - torchaudio==0.12.1
    - grpcio==1.43.0
    - ray[default]==2.2.0
    - ray[rllib]==2.2.0
    - ray[tune]==2.2.0
    - ray[air]==2.2.0
    - ale-py==0.7.5
    - gym==0.23.0
    - gym-notices==0.0.7
    - gym[accept-rom-license]==0.23.0
    - Gymnasium==0.26.3
    - gymnasium-notices==0.0.1
    - rfc3339==6.2
    - numpy==1.23.5
    - pydantic<2
    - aiohttp-cors==0.7.0
    - aiorwlock==1.3.0
    - arrow==1.2.2
    - asgiref==3.5.2
    - blessed==1.20.0
    - boto3==1.23.10
    - botocore==1.26.10
    - cachetools==5.1.0
    - click==8.0.4
    - colorful==0.5.4
    - contourpy==1.0.6
    - cycler==0.11.0
    - distlib==0.3.6
    - dm-tree==0.1.7
    - dynaconf==3.1.9
    - fonttools==4.37.1
    - fqdn==1.5.1
    - func-timeout==4.3.5
    - google-api-core==2.10.2
    - google-auth==2.16.1
    - googleapis-common-protos==1.57.0
    - gputil==1.4.0
    - gutils==0.1.9
    - h11==0.13.0
    - imageio==2.25.1
    - importlib-metadata==5.1.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jmespath==1.0.1
    - jsonpointer==2.3
    - Farama-Notifications==0.0.4
    - absl-py==1.4.0
    - distro==1.7.0
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - libtorrent==2.0.7
    - llvmlite==0.39.0
    - lz4==4.0.2
    - markdown==3.4.1
    - matplotlib==3.7.0
    - msgpack==1.0.4
    - networkx==2.8.8
    - numba==0.56.4
    - opencensus==0.11.0
    - opencensus-context==0.1.3
    - packaging==21.3
    - pillow==9.3.0
    - prometheus-client==0.13.0
    - protobuf==3.20.3
    - py-spy==0.3.12
    - pyarrow==6.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - pywavelets==1.3.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - s3transfer==0.5.2
    - nvidia-ml-py3==7.352.0
    - scikit-image==0.19.3
    - scikit-learn==1.2.1
    - scipy==1.9.3
    - shap==0.41.0
    - slicer==0.0.7
    - smart-open==6.2.0
    - sqlalchemy==1.4.46
    - starlette==0.25.0
    - tensorboardx==2.6
    - threadpoolctl==3.1.0
    - tifffile==2023.2.3
    - uri-template==1.2.0
    - uvicorn==0.16.0
    - virtualenv==20.19.0
    - webcolors==1.11.1
    - widgetsnbextension==4.0.5
    - gpustat
    - opencv-python