name: gymnasium
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - opencv
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - aiohttp==3.9.1
      - aiohttp-cors==0.7.0
      - aiorwlock==1.3.0
      - aiosignal==1.3.1
      - alembic==1.13.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - Babel==2.13.1
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - blessed==1.20.0
      - blinker==1.7.0
      - boto3==1.33.8
      - botocore==1.33.8
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorful==0.5.5
      - comm==0.2.0
      - aiohttp==3.9.1
      - aiohttp-cors==0.7.0
      - aiorwlock==1.3.0
      - aiosignal==1.3.1
      - alembic==1.13.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - Babel==2.13.1
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - blessed==1.20.0
      - blinker==1.7.0
      - boto3==1.33.8
      - botocore==1.33.8
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorful==0.5.5
      - comm==0.2.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - databricks-cli==0.18.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - Deprecated==1.2.14
      - distlib==0.3.7
      - dm-tree==0.1.8
      - docker==6.1.3
      - dynaconf==3.2.4
      - entrypoints==0.4
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - Farama-Notifications==0.0.4
      - fastapi==0.104.1
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - Flask==3.0.0
      - fonttools==4.46.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.12.1
      - gitdb==4.0.11
      - GitPython==3.1.40
      - google-api-core==2.14.0
      - google-auth==2.25.1
      - googleapis-common-protos==1.61.0
      - gpustat==1.1.1
      - GPUtil==1.4.0
      - greenlet==3.0.1
      - grpcio==1.59.3
      - gunicorn==21.2.0
      - gymnasium==0.28.1
      - h11==0.14.0
      - httptools==0.6.1
      - idna==3.6
      - imageio==2.33.0
      - importlib-metadata==6.11.0
      - importlib-resources==6.1.1
      - ipykernel==6.27.1
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jax-jumpy==1.0.0
      - jedi==0.19.1
      - Jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter_client==8.6.0
      - jupyter_core==5.5.0
      - jupyter_server==2.12.0
      - jupyter_server_terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab_pygments==0.3.0
      - jupyterlab_server==2.25.2
      - kiwisolver==1.4.5
      - lazy_loader==0.3
      - lz4==4.3.2
      - Mako==1.3.0
      - Markdown==3.5.1
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - minigrid==2.3.1
      - mistune==3.0.2
      - mpmath==1.3.0
      - mpu==0.23.1
      - msgpack==1.0.7
      - multidict==6.0.4
      - nbclassic==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.12.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - notebook==7.0.6
      - notebook_shim==0.2.3
      - nvidia-ml-py==12.535.133
      - oauthlib==3.2.2
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - opentelemetry-api==1.21.0
      - opentelemetry-exporter-otlp==1.21.0
      - opentelemetry-exporter-otlp-proto-common==1.21.0
      - opentelemetry-exporter-otlp-proto-grpc==1.21.0
      - opentelemetry-exporter-otlp-proto-http==1.21.0
      - opentelemetry-proto==1.21.0
      - opentelemetry-sdk==1.21.0
      - opentelemetry-semantic-conventions==0.42b0
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.9.0
      - Pillow==10.1.0
      - platformdirs==3.11.0
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - protobuf==4.25.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-spy==0.3.14
      - pyarrow==14.0.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==1.10.13
      - pygame==2.5.2
      - Pygments==2.17.2
      - PyJWT==2.8.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - PyYAML==6.0.1
      - pyzmq==25.1.2
      - querystring-parser==1.2.4
      - ray[all]==2.8.0
      - referencing==0.31.1
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.13.2
      - rsa==4.9
      - s3transfer==0.8.2
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - Send2Trash==1.8.2
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - SQLAlchemy==2.0.23
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - starlette==0.27.0
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboardX==2.6.2.2
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==1.12.1+cu113
      - torchaudio==0.12.1
      - torchvision==0.13.1+cu113
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.0
      - triton==2.1.0
      - typer==0.9.0
      - types-python-dateutil==2.8.19.14
      - typing_extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==1.26.18
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - virtualenv==20.21.0
      - watchfiles==0.21.0
      - wcwidth==0.2.12
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==12.0
      - Werkzeug==3.0.1
      - wrapt==1.16.0
      - yarl==1.9.3
      - zipp==3.17.0