name: hpc
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - setuptools==67.0
      - torch==1.12.1+cu113
      - torchvision==0.13.1+cu113
      - torchaudio==0.12.1
      - grpcio==1.48.1
      - ray==2.2.0
      - ray[default]==2.2.0
      - ray[rllib]==2.2.0
      - ray[tune]==2.2.0
      - ray[air]==2.2.0
      - grpcio==1.48.2
      - ale-py==0.7.5
      - gym==0.23.1
      - numpy==1.21.4
      - pydantic<2
      - mlflow
      - pyyaml
      - func_timeout
      - tqdm
      - dynaconf
      - gym[accept-rom-license]
      - gputil