mlflow:
  experiment: "SpaceInvaders"
  url: "https://seventheli-mlflow.eu.cpolar.io/"
  user: "AutoDL"
dqn:
  env: SpaceInvadersNoFrameskip
  run: DQN
  hyper_parameters:
    framework: torch
    double_q: false
    dueling: false
    exploration_config:
      epsilon_timesteps: 200000
      final_epsilon: 0.01
    num_atoms: 1
    noisy: false
    replay_buffer_config:
      type: ReplayBuffer
      capacity: 1000000
    num_steps_sampled_before_learning_starts: 20000
    n_step: 1
    target_network_update_freq: 8000
    lr: .0000625
    adam_epsilon: .00015
    hiddens: [512]
    rollout_fragment_length: 4
    train_batch_size: 32
    num_gpus: 1
    num_cpus: 5
    num_workers: 1
    num_gpus_per_worker: 0.1
    min_sample_timesteps_per_iteration: 10000
log:
  save_file: "/root/seventheli/logging/SpaceInvaders"
  save_checkout: "/home/seventheli/checkpoints/SpaceInvaders"
  max_time: 360000
  log: 5