dqn:
  env: TennisNoFrameskip-v4
  hyper_parameters:
    adam_epsilon: 0.00015
    double_q: false
    dueling: false
    exploration_config:
      epsilon_timesteps: 200000
      final_epsilon: 0.01
    framework: torch
    hiddens:
    - 512
    lr: 6.25e-05
    min_sample_timesteps_per_iteration: 10000
    n_step: 1
    noisy: false
    num_atoms: 1
    num_gpus: 1
    num_steps_sampled_before_learning_starts: 20000
    replay_buffer_config:
      capacity: 1000000
      type: ReplayBuffer
    rollout_fragment_length: 4
    target_network_update_freq: 8000
    train_batch_size: 32
  run: DQN
log:
  log: 100
  max_time: 360000
  save_checkout: /jmain02/home/J2AD006/jxb06/cxz46-jxb06/checkpoints/Tennis
  save_file: /jmain02/home/J2AD006/jxb06/cxz46-jxb06/logging/Tennis
