atari-basic-dqn:
  env: SpaceInvadersNoFrameskip
  run: DQN
  stop:
    sampler_results/episode_reward_mean: 20
    time_total_s: 180000
  config:
    double_q: false
    dueling: false
    num_atoms: 1
    noisy: false
    n_step: 1
    lr: .0000625
    adam_epsilon: .00015
    hiddens: [ 512 ]
    num_steps_sampled_before_learning_starts: 20000
    # Extra
    num_gpus: 0.2
    framework: "torch"
    # DQN
    num_envs_per_worker: 1
    num_gpus_per_worker: 0
    rollout_fragment_length: 4
    train_batch_size: 32
    target_network_update_freq: 8000
    min_sample_timesteps_per_iteration: 10000
    replay_buffer_config:
      type: 'ReplayBuffer'
      capacity: 1000000