hyper_parameters:
  hiddens: [ ]
  framework: torch
  double_q: true
  dueling: false
  noisy: false
  adam_epsilon: .00015
  exploration_config:
    epsilon_timesteps: 200000
    final_epsilon: 0.01
  lr: 0.0001
  n_step: 3
  num_atoms: 1
  replay_buffer_config:
    capacity: 2000000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 1
    type: MultiAgentPrioritizedReplayBuffer
  resources:
    num_gpus: 1
    num_cpus_per_worker: 1
    num_gpus_per_worker: 0.1
    num_envs_per_worker: 64
    num_cpus_per_learner_worker: 1
    num_gpus_per_learner_worker: 1
  num_workers: 10
  num_steps_sampled_before_learning_starts: 20000
  rollout_fragment_length: 32
  target_network_update_freq: 50000
  train_batch_size: 1024
  min_sample_timesteps_per_iteration: 25000
run: APEX
log:
  max_run: 100
  log: 100
  max_time: 360000
