hyper_parameters:
  adam_epsilon: .00015
  double_q: true
  dueling: false
  exploration_config:
    epsilon_timesteps: 200000
    final_epsilon: 0.01
  framework: torch
  hiddens: [ 512 ]
  lr: .0001
  min_sample_timesteps_per_iteration: 25000
  noisy: false
  n_step: 3
  num_atoms: 1
  num_cpus_per_worker: 1
  num_envs_per_worker: 8
  num_gpus: 1
  num_gpus_per_worker: 0.01
  num_workers: 5
  replay_buffer_config:
    capacity: 1000000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 1
    type: 'MultiAgentPrioritizedReplayBuffer'
  rollout_fragment_length: 20
  target_network_update_freq: 50000
  train_batch_size: 512
  num_steps_sampled_before_learning_starts: 100000
run: APEX
log:
  max_run: 20000
  log: 10
  max_time: 360000
