mlflow:
  experiment: "Eval_Diff_BZ_8U_1G"
  url: "https://seventheli-mlflow.eu.cpolar.io/"
  user: "User"
dqn:
  env: BreakoutNoFrameskip-v4
  run: DQN
  hyper_parameters:
    double_q: false
    dueling: false
    num_atoms: 1
    noisy: false
    n_step: 3
    lr: .0001
    adam_epsilon: .00015
    hiddens: [ 512 ]
    # Extra
    num_gpus: 1
    framework: "torch"
    evaluation_duration_unit: "episodes"
    rollout_fragment_length: 20
    # DQN
    num_workers: 1
    num_envs_per_worker: 8
    num_cpus_per_worker: 8
    num_gpus_per_worker: 1
    train_batch_size: 512
    target_network_update_freq: 50000
    min_sample_timesteps_per_iteration: 25000
    replay_buffer_config:
      capacity: 1000000
      prioritized_replay_beta: 1
      prioritized_replay_alpha: 0.5
control:
  score: 400
  min_time: 3600
  max_time: 3600
  log: 1
  save: 100