apex:
  env: QbertNoFrameskip-v4
  hyper_parameters:
    adam_epsilon: 0.00015
    double_q: true
    dueling: false
    exploration_config:
      epsilon_timesteps: 200000
      final_epsilon: 0.01
    framework: torch
    hiddens:
    - 512
    lr: 0.0001
    min_sample_timesteps_per_iteration: 25000
    n_step: 3
    noisy: false
    num_atoms: 1
    num_cpus_per_worker: 1
    num_envs_per_worker: 8
    num_gpus: 1
    num_gpus_per_worker: 0.1
    num_workers: 4
    replay_buffer_config:
      capacity: 1000000
      prioritized_replay_alpha: 0.5
      prioritized_replay_beta: 1
      type: MultiAgentPrioritizedReplayBuffer
    rollout_fragment_length: 20
    target_network_update_freq: 50000
    train_batch_size: 512
  run: apex
log:
  log: 100
  max_time: 3600
